const VALID_STATUSES = ["TODO", "IN_PROGRESS", "UNDER_REVIEW", "DONE"];
const VALID_PRIORITIES = ["LOW", "MEDIUM", "HIGH"];
const VALID_ACTIVITY_TYPER=["TASK_CREATED","STATUS_CHANGE","ASSIGNMENT_CHANGE","DUE_DATE_CHANGE","PRIORITY_CHANGE","TITLE_CHANGE","DESCRIPTION_CHANGE","COMMENT_ADDED","COMMENT_UPDATED","COMMENT_DELETED"];


module.exports = {
  VALID_STATUSES,
  VALID_PRIORITIES,
  VALID_ACTIVITY_TYPER
};
